// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4deming_flat_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4deming_flat_power_beta_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4deming_flat_power_normal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4deming_flat_power_point_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4deming_normal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4deming_uniform_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4deming_uniform_power_beta_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4deming_uniform_power_normal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4deming_uniform_power_point_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4deming_flat_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4deming_flat_mod, 0},
    {"_rcpp_module_boot_stan_fit4deming_flat_power_beta_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4deming_flat_power_beta_mod, 0},
    {"_rcpp_module_boot_stan_fit4deming_flat_power_normal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4deming_flat_power_normal_mod, 0},
    {"_rcpp_module_boot_stan_fit4deming_flat_power_point_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4deming_flat_power_point_mod, 0},
    {"_rcpp_module_boot_stan_fit4deming_normal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4deming_normal_mod, 0},
    {"_rcpp_module_boot_stan_fit4deming_uniform_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4deming_uniform_mod, 0},
    {"_rcpp_module_boot_stan_fit4deming_uniform_power_beta_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4deming_uniform_power_beta_mod, 0},
    {"_rcpp_module_boot_stan_fit4deming_uniform_power_normal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4deming_uniform_power_normal_mod, 0},
    {"_rcpp_module_boot_stan_fit4deming_uniform_power_point_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4deming_uniform_power_point_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesDeming(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
